# Generated by Django 2.2.1 on 2019-06-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='ISO 639-1 code')),
            ],
        ),
    ]
