# Generated by Django 2.2.1 on 2019-06-21 07:42

from django.db import migrations


def forwards_func(apps, schema_editor):
    Language = apps.get_model("core", "Language")
    Language.objects.bulk_create([
        Language(name="english", code="en"),
        Language(name="russian", code="ru"),
        Language(name="spanish", code="es"),
        Language(name="chinese", code="zh"),
    ])


def reverse_func(apps, schema_editor):
    Language = apps.get_model("core", "Language")
    Language.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
