# Generated by Django 2.2.1 on 2019-07-01 08:11

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import libs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('core', '0002_auto_20190621_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', libs.fields.MoneyField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_group', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sex', libs.fields.ChoicesField(blank=True, choices=[(1, 'female'), (2, 'male')], default=None, null=True)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('phone', libs.fields.PhoneNumberField(blank=True, default=None, max_length=16, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=30)),
                ('city', models.CharField(blank=True, default='', max_length=30)),
                ('about', models.TextField(blank=True, default='')),
                ('additional', models.TextField(blank=True, default='')),
                ('has_driving_license', models.BooleanField(default=False)),
                ('driving_experience', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to='avatar')),
                ('account', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
            ],
        ),
        migrations.CreateModel(
            name='GuideProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('status', libs.fields.ChoicesField(choices=[(1, 'created'), (2, 'confirmed'), (3, 'rejected'), (4, 'completed'), (5, 'canceled')], default=0)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, to='core.Client')),
            ],
        ),
        migrations.CreateModel(
            name='TripRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('type', libs.fields.ChoicesField(choices=[(1, 'journey'), (2, 'entertainment'), (3, 'excursion')], default=0)),
                ('country', models.CharField(blank=True, default='', max_length=30)),
                ('city', models.CharField(blank=True, default='', max_length=30)),
                ('nop', models.PositiveIntegerField(verbose_name='Number of participants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GuideProfile')),
            ],
        ),
        migrations.CreateModel(
            name='TripRoutePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpp', libs.fields.MoneyField(decimal_places=2, max_digits=8)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326)),
                ('title', models.CharField(blank=True, default='', max_length=1024)),
                ('description', models.TextField(blank=True, default='')),
                ('trip_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TripRoute')),
            ],
        ),
        migrations.CreateModel(
            name='TripRoutePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trip-route-picture')),
                ('is_poster', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TripRoute')),
            ],
        ),
        migrations.CreateModel(
            name='TripRouteComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
                ('trip_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TripRoute')),
            ],
        ),
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', libs.fields.ChoicesField(choices=[(1, 'created'), (2, 'accepted'), (3, 'declined'), (4, 'payed'), (5, 'confirmed'), (6, 'rejected'), (7, 'completed'), (8, 'canceled')], default=0)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', libs.fields.MoneyField(decimal_places=2, max_digits=8)),
                ('is_funded', models.BooleanField(default=False)),
                ('is_hold', models.BooleanField()),
                ('trip_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TripRequest')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TripRoute'),
        ),
        migrations.CreateModel(
            name='ClientPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250)),
                ('image', models.ImageField(upload_to='client-picture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='guide_profile',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.GuideProfile'),
        ),
        migrations.AddField(
            model_name='client',
            name='language',
            field=models.ForeignKey(default='en', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Language'),
        ),
        migrations.AddField(
            model_name='client',
            name='languages_speak',
            field=models.ManyToManyField(blank=True, related_name='languages_speak', to='core.Language'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Chat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
            ],
        ),
        migrations.CreateModel(
            name='AccountWithdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', libs.fields.MoneyField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', libs.fields.ChoicesField(choices=[(1, 'created'), (2, 'accepted'), (3, 'declined')], default=0)),
                ('reason', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', libs.fields.MoneyField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_at', models.DateTimeField()),
                ('status', libs.fields.ChoicesField(choices=[(1, 'created'), (2, 'accepted'), (3, 'declined')], default=0)),
                ('reason', models.TextField(blank=True, default='')),
                ('account_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='core.Account')),
                ('account_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='core.Account')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='AccountReplenishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', libs.fields.MoneyField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', libs.fields.ChoicesField(choices=[(1, 'created'), (2, 'accepted'), (3, 'declined')], default=0)),
                ('reason', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ChatToClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(blank=True, default=None, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Chat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
            ],
            options={
                'unique_together': {('chat', 'client')},
            },
        ),
    ]
