server {
    listen 80;
    server_name test.easyguide.me;

    location /static {
        alias /srv/test/storage/static;
    }

    location /media {
        alias /srv/test/storage/media;
    }

    location / {
        proxy_pass http://localhost:50002;
    }
}

server {
    listen 5432;
    server_name db.test.easyguide.me;

    location / {
        proxy_pass http://localhost:50012;
    }
}
